### ISSUE TITLE
rukkit updateコマンドの廃止

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/rukkit#18]
updateに時間がかかりすぎるので、いっそ廃止したい

## 現状

- `/rukkit update` コマンドにてアップデート実行

同期的にupdateするので時間がかかる。主に`git pull`, `bundle install`。

## 案

webhook用エンドポイントを用意しておいて、githubからのhook通知を受けて裏で非同期に自動update

**Comment by ujihisa** [comment]
:+1:

**Comment by kamichidu** [comment]
非同期updateの仕様案:

`JRubyPlugin#jruby` のインスタンスを切り替えるだけでupdateを行うようにする。
インスタンスを切り替える準備が整うまでは現行の環境で動きつつ、準備が整い次第新環境のインスタンスへと切り替える。

`/rukkit update` の際に、 `git pull` および `bundle install` さらにjrubyの新環境でそれらをロードし、ロードが終わり次第内部でインスタンスの切り替えを行う。

この変更により、rukkit pluginの内部状態が保持されなくなるが、これについては基本的にredis等で永続化すべきものと考え、rukkit pluginはstatelessで動くように作ることとなる。
(thx, thinca)

**Comment by kamichidu** [comment]
追記:

`/rukkit update` のコマンドは残したままとする。
だが、コマンドを発行したら即updateがかかる訳ではなく、update要求を出すのみのコマンドとなる。

**Comment by supermomonga** [comment]
おおお、良さそう！
github連携は別issueにしますね。

**Comment by kamichidu** [comment]
非同期updateが稼働してるので、これも閉じちゃっていいかな。
問題あれば再openしてください。

**Comment by deris** [comment]
kamichidu++
非同期update快適に動いてます :+1:
