### ISSUE TITLE
Add a feature: auto-reload

### ISSUE THREAD

**Issue by kamichidu** [supermomonga/rukkit#19]
開発用機能として、rukkit pluginが変更された場合に自動でreloadする機能を追加する。

1. リファクタリング

    core.rbにあるupdate周りの処理を、java側へ移動

1. 非同期updateの実装

    #18 にある非同期updateを実装する

1. ファイルシステムの変更を検知し、非同期updateを実行する処理の実装

**Comment by supermomonga** [comment]
>ファイルシステムの変更を検知し、非同期updateを実行する処理の実装

git pull とかした時は複数ファイルが連続して上書きされることあると思うけど、そのあたりのハンドリングめんどくさそう
ファイルへの変更があってからn秒間新たな変更がなかったらupdate、とか？

**Comment by ujihisa** [comment]
3は不要かな、非同期updateするためのコマンドがあれば、あとは各自でwatchさせればよいので。

Vimで開発してるならVimから、そうでなくてもwatchコマンドとかそういうのでやればよさそう

**Comment by supermomonga** [comment]
確かに

**Comment by supermomonga** [comment]
運用時は自動updateはgithub webhook連携とかでいい気もする。

あ、それ実装すれば、ローカルでのテスト時もVimなどからローカルのHTTPサーバにgithub webhook互換のリクエスト飛ばせばいいか。

**Comment by kamichidu** [comment]
流れとして、3は不要かな。
作るべきは、github webhookのリクエストを受け取る部分？

> 各自でwatchさせればよい
これって、良さそうなツールありますっけ (windowsさん...

**Comment by supermomonga** [comment]
Guardとかは？

**Comment by kamichidu** [comment]
> Guardとかは？

ないことはないのですね。
であれば、3についてはrukkitでやって欲しいという要望があれば実施する形で、今は実装しない方向で行きます。

**Comment by supermomonga** [comment]
(〃`l _ l´)ゞ☆

**Comment by kamichidu** [comment]
1については大体終わってデプロイ済です。
2については今日か明日あたりでやってしまいたい。

**Comment by supermomonga** [comment]
すごいヾ(l ヮ l〃)ﾉﾞ三ヾ(〃l ヮ l)ﾉﾞ

**Comment by kamichidu** [comment]
非同期updateの実装、デプロイまで終わってるので閉じます。
何かあれば別issueで。

**Comment by supermomonga** [comment]
:+1:
