### ISSUE TITLE
install rubygems でGemspecのタイムスタンプ見て更新が必要なときだけアレする

### ISSUE THREAD

**Issue by kamichidu** [supermomonga/rukkit#26]

**Comment by ujihisa** [comment]
意図を推測してタイトル書き換えてみました

**Comment by kamichidu** [comment]
thx!

**Comment by supermomonga** [comment]
おお、よさそう！

**Comment by supermomonga** [comment]
>install rubygems でGemspecのタイムスタンプ見て更新が必要なときだけアレする

s/install rubygems/bundle install/

s/Gemspec/Gemfile/

意図としてはこうかな？

**Comment by raa0121** [comment]
基本的に bundle install ってキャッシュ見て、入ってたら
`Using hoge...` ってなるので、そんなに気にしなくていい気がする

**Comment by supermomonga** [comment]
それでも割と5秒くらいかからない？特にjrubyだとjvm起動するし、そこを短縮したいって話かと思った

**Comment by kamichidu** [comment]
jvm起動するので、そこの引っかかりをなくしたい意図です。
私の手元では、5秒程度かかっているので。

**Comment by raa0121** [comment]
GemfileのMD5でも取っておいて、更新があったらbundle install させればいいのかな

**Comment by raa0121** [comment]
MD5 より git log --pretty=oneline Gemfile してハッシュGit側のハッシュ取ったほうが良さそう

**Comment by kamichidu** [comment]
http://docs.oracle.com/javase/7/docs/api/java/io/File.html#lastModified()

これで必要十分だと思う

**Comment by raa0121** [comment]
あー いや、取得する方法はなんでもいいんですが、前回更新の日時を記録しておく必要があるわけですよ Redisに入れます？

**Comment by kamichidu** [comment]
1. 更新時刻の取得
2. 取得した更新時刻をJRubyPluginのインスタンスフィールドに持つ
3. bundle install時、インスタンスフィールドに保存した時刻と今回取得した時刻を比較し、違ったときだけ実行

これで問題ないと思います。reload時や初回起動時に実行されますが、それはむしろ実行されないと困る場面が出そうなのと、実用的にはインスタンスフィールドに持つので十分だろうという考えです。

**Comment by kamichidu** [comment]
前提に齟齬があったので、インスタンスフィールドでなくredisのほうが良さそう。

**Comment by kamichidu** [comment]
既に稼働しているので閉じます。
問題あれば再オープン願います。

**Comment by supermomonga** [comment]
そうえいばこれ、redis使って更新日時判定しなくても、git pullする前のGemfile.lockとgit pull後のGemfile.lockのdiff見れば行けそうな感じする
